-- Disable RLS for all tables
ALTER TABLE disciplinas DISABLE ROW LEVEL SECURITY;
ALTER TABLE horarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE tarefas DISABLE ROW LEVEL SECURITY;
ALTER TABLE anotacoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE revisoes DISABLE ROW LEVEL SECURITY;
